version: 2

sources:
  - name: preppin_data_input_files
    description: >
      Source/Input files provided by Preppin' Data authors for weekly challenges.
      Source load scripts can be found [here](https://github.com/jharris126/preppin-data-dbt/tree/master/data_ingestion).
    loader: custom python
    loaded_at_field: _loaded_at
    schema: main
    tables:
      - name: src_week_202242
        description: >
          Source file for [Preppin' Data 2022 Week 42](https://preppindata.blogspot.com/2022/10/2022-week-42-missing-training-data.html).
          This week has only 1 source file.
          Link to input file: [here](https://drive.google.com/file/d/1d4ItvcaPATxbFevMOfAIXXpchOh-09D_/view?usp=sharing)
          Link to load script: [here](https://github.com/jharris126/preppin-data-dbt/blob/master/data_ingestion/2022_week_42.py)
        columns:
          - name: Player
            type: VARCHAR
          - name: Session
            type: VARCHAR
          - name: Date
            type: DATE
          - name: Score
            type: BIGINT
          - name: _loaded_at
            type: DATETIME
            description: >
              Timestamp generated by data_ingestion python script. Stores the time the data was loaded into this table.

      - name: src_week_202239
        description: >
          Source file for [Preppin' Data 2022 Week 39](https://preppindata.blogspot.com/2022/09/2022-week-39-filling-in-for-hr.html).
          This week has only 1 source file.
          Link to input file: [here](https://drive.google.com/file/d/1p5Dn8DR4XDPmfEv4MQL-1C0EJZO4t97P/view)
          Link to load script: [here](https://github.com/jharris126/preppin-data-dbt/blob/master/data_ingestion/2022_week_39.py)
        columns:
          - name: ﻿Record ID
            type: BIGINT
          - name: Employee
            type: VARCHAR
          - name: Work Level
            type: VARCHAR
          - name: Stage
            type: VARCHAR
          - name: Date
            type: DATE
          - name: _loaded_at
            type: DATETIME
            description: >
              Timestamp generated by data_ingestion python script. Stores the time the data was loaded into this table.

      - name: src_week_202243
        description: >
          Source file for [Preppin' Data 2022 Week 43](https://preppindata.blogspot.com/2022/10/2022-week-43-missing-training-data-20.html).
          This week has only 1 source file.
          Link to input file: [here](https://drive.google.com/file/d/1lyYO70ooCldGLT8yPHoiiHn_z7S-CN7V/view)
          Link to load script: [here](https://github.com/jharris126/preppin-data-dbt/blob/master/data_ingestion/2022_week_43.py)
        columns:
          - name: Player
            type: VARCHAR
          - name: Session
            type: VARCHAR
          - name: Date
            type: DATE
          - name: Score
            type: BIGINT
          - name: _loaded_at
            type: DATETIME
            description: >
              Timestamp generated by data_ingestion python script. Stores the time the data was loaded into this table.