version: 2

models:
  - name: 202242_solution
    description: >
      Solution SQL definition for [Preppin' Data 2022 Week 42](https://preppindata.blogspot.com/2022/10/2022-week-42-missing-training-data.html).
      Created as view and exported as [202242_solution_output.csv](https://github.com/jharris126/preppin-data-dbt/blob/master/solution_outputs/202242_solution_output.csv) in [/preppin-data-dbt/solution_outputs](https://github.com/jharris126/preppin-data-dbt/tree/master/solution_outputs) folder.
      All solutions sql files automatically generate a `.csv` output file when run using the [model_to_csv macro](#!/macro/macro.preppin_data.model_to_csv).
    columns:
      - name: player
        type: VARCHAR
      - name: session
        type: VARCHAR
      - name: session_date
        type: DATE
      - name: score
        type: BIGINT
        tests:
          - not_null
      - name: flag
        type: VARCHAR
        tests:
          - accepted_values:
              values: [Actual, Carried Over]

  - name: 202239_solution
    description: >
      Solution SQL definition for [Preppin' Data 2022 Week 39](https://preppindata.blogspot.com/2022/09/2022-week-39-filling-in-for-hr.html).
      Created as view and exported as [202239_solution_output.csv](https://github.com/jharris126/preppin-data-dbt/blob/master/solution_outputs/202239_solution_output.csv) in [/preppin-data-dbt/solution_outputs](https://github.com/jharris126/preppin-data-dbt/tree/master/solution_outputs) folder.
      All solutions sql files automatically generate a `.csv` output file when run using the [model_to_csv macro](#!/macro/macro.preppin_data.model_to_csv).
    columns:
      - name: record_id
        type: BIGINT
        tests:
          - unique
          - not_null
      - name: employee
        type: VARCHAR
        tests:
          - not_null
      - name: work_level
        type: VARCHAR
        tests:
          - not_null
      - name: stage
        type: VARCHAR
      - name: date
        type: DATE

  - name: 202243_solution
    description: >
      Solution SQL definition for [Preppin' Data 2022 Week 43](https://preppindata.blogspot.com/2022/10/2022-week-43-missing-training-data-20.html).
      Created as view and exported as [202243_solution_output.csv](https://github.com/jharris126/preppin-data-dbt/blob/master/solution_outputs/202243_solution_output.csv) in [/preppin-data-dbt/solution_outputs](https://github.com/jharris126/preppin-data-dbt/tree/master/solution_outputs) folder.
      All solutions sql files automatically generate a `.csv` output file when run using the [model_to_csv macro](#!/macro/macro.preppin_data.model_to_csv).
    columns:
      - name: player
        type: VARCHAR
      - name: session
        type: VARCHAR
      - name: session_date
        type: DATE
      - name: score
        type: BIGINT
        tests:
          - not_null
      - name: flag
        type: VARCHAR
        tests:
          - accepted_values:
              values: [Actual, Carried Over, Pre First Session]

  - name: 202201_solution
    description: >
      Solution SQL definition for [Preppin' Data 2022 Week 1](https://preppindata.blogspot.com/2022/01/2022-week-1-prep-school-parental.html).
      Created as view and exported as [202201_solution_output.csv](https://github.com/jharris126/preppin-data-dbt/blob/master/solution_outputs/202201_solution_output.csv) in [/preppin-data-dbt/solution_outputs](https://github.com/jharris126/preppin-data-dbt/tree/master/solution_outputs) folder.
      All solutions sql files automatically generate a `.csv` output file when run using the [model_to_csv macro](#!/macro/macro.preppin_data.model_to_csv).
    columns:
      - name: academic_year
        type: INTEGER
      - name: pupils_name
        type: VARCHAR
      - name: parental_contact_full_name
        type: VARCHAR
      - name: parental_contact_email_address
        type: VARCHAR

  - name: 202244_solution
    description: >
      Solution SQL definition for [Preppin' Data 2022 Week 44](https://preppindata.blogspot.com/2022/11/2022-week-44-creating-order-ids.html).
      Created as view and exported as [202244_solution_output.csv](https://github.com/jharris126/preppin-data-dbt/blob/master/solution_outputs/202244_solution_output.csv) in [/preppin-data-dbt/solution_outputs](https://github.com/jharris126/preppin-data-dbt/tree/master/solution_outputs) folder.
      All solutions sql files automatically generate a `.csv` output file when run using the [model_to_csv macro](#!/macro/macro.preppin_data.model_to_csv).
    columns:
      - name: order_id
        type: VARCHAR
        tests:
          - not_null
          - unique
      - name: order_number
        type: BIGINT
        tests:
          - not_null
      - name: customer
        type: VARCHAR
        tests:
          - not_null
      - name: order_date
        type: DATE
        tests:
          - not_null

  - name: 202245_solution
    description: >
      Solution SQL definition for [Preppin' Data 2022 Week 45](https://preppindata.blogspot.com/2022/11/2022-week-45-strange-table-structure.html).
      Created as view and exported as [202245_solution_output.csv](https://github.com/jharris126/preppin-data-dbt/blob/master/solution_outputs/202245_solution_output.csv) in [/preppin-data-dbt/solution_outputs](https://github.com/jharris126/preppin-data-dbt/tree/master/solution_outputs) folder.
      All solutions sql files automatically generate a `.csv` output file when run using the [model_to_csv macro](#!/macro/macro.preppin_data.model_to_csv).
    columns:
      - name: store
        type: VARCHAR
        tests:
          - not_null
          - accepted_values:
              values: [Dulwich, Wimbledon, Notting Hill, Lewisham]
      - name: date
        type: DATE
        tests:
          - not_null
      - name: sales
        type: BIGINT
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: '> 0'
      - name: profit
        type: BIGINT
        tests:
          - not_null
